config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'home#index'

  resources :comments
  resources :users
  resources :posts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :content, presence: true
  validates :content, length: { maximum: 140 }
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments

  has_one_attached :image

  validates :title, :body, presence: true
  validate :correct_image_file_type

  def capitalized_title
    title.capitalize
  end

  def self.titles
    Post.all.pluck(:title)
  end

  private

  def correct_image_file_type
    if image.attached? && ['image/png', 'image/jpg', 'image/jpeg'].exclude?(image.content_type)
      errors.add(:image, 'Must be jpg or png file')
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts

  has_one_attached :avatar

  validates :name, presence: true
  validates :name, format: /[A-Z][a-z]*/

  scope :created_today, -> { where("created_at > ?", Date.today.beginning_of_day) }
  scope :with_name, ->(name) { where("name LIKE ?", "#{name}%")}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :avatar])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, only: :create

  def index
    @comments = Comment.all
  end

  def new
    @comment = Comment.new
  end

  def edit
    @comment = Comment.find(params[:id])
  end

  def create
    @comment = Comment.new(comment_params.merge(user: current_user))
    if @comment.save
      redirect_to comments_path
    else
      render :new
    end
  end

  def update
    @comment = Comment.find(params[:id])
    if @comment.update(comment_params)
      redirect_to comments_path
    else
      render :edit
    end
  end

  def show
    @comment = Comment.find(params[:id])
  end

  def destroy
    @comment = Comment.find(params[:id])
    if @comment.destroy
      flash[:notice] = 'Comment has been destroyed'
      redirect_to comments_path
    else
      flash[:alert] = 'Something went wrong'
      redirect_to comments_path
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:content, :post_id, :user_id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @message = 'Cześć'
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: :create

  def index
    @posts = Posts::Sort.new(Posts::Recent.call).call.page(params[:page])
  end

  def new
    @post = Post.new
  end

  def edit
    @post = Post.find(params[:id])
  end

  def create
    Posts::Create.new(post_params.merge(user: current_user)).call
    redirect_to posts_path
  rescue ActiveRecord::RecordInvalid => invalid
    @post = invalid.record
    render :new
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to posts_path
    else
      render :edit
    end
  end

  def show
    @post = Post.find(params[:id])
    @comments = Comments::Sort.new(Comments::Post.new(@post.id).call).call
  end

  def destroy
    @post = Post.find(params[:id])
    if Posts::Destroy.new(@post).call
      flash[:notice] = 'Post has been destroyed'
      redirect_to posts_path
    else
      flash[:alert] = 'Something went wrong'
      redirect_to posts_path
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :body, :user_id, :image)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
    @user = User.new
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to users_path
    else
      render :new
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to users_path
    else
      render :edit
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def destroy
    @user = User.find(params[:id])
    if @user.destroy
      flash[:notice] = 'User has been destroyed'
      redirect_to users_path
    else
      flash[:alert] = 'Something went wrong'
      redirect_to users_path
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<%= form_with model: @comment do |form| %>
  <div class='mb-3 col-md-2'>
    <%= form.label :content %>
    <%= form.text_field :content, class: 'form-control' %>
  </div>
  <div class='mb-3 col-md-2'>
    <%= form.label :post_id %>
    <%= form.collection_select :post_id, Post.all.order(:title), :id, :title, {}, class: 'form-select' %>
  </div>
  <%= form.submit 'Save', class: 'btn btn-success' %>
<% end %>

app/views/comments/edit.html.erb
<%= render 'comment' %>

app/views/comments/index.html.erb
<%= link_to 'Add New Comment', new_comment_path, class: 'btn btn-primary link-warning' %>

<h1>Comments</h1>
<table class="table">
  <tr>
    <th>Comment ID</th>
    <th>Comment Content</th>
    <th>Edit</th>
    <th>Delete</th>
  </tr>
  <% @comments.each do |comment| %>
    <tr>
      <td><%= comment.id %></td>
      <td><%= link_to comment.content, comment_path(comment) %></td>
      <td><%= link_to 'Edit Comment', edit_comment_path(comment) %></td>
      <td><%= link_to 'Delete Comment', comment_path(comment), method: :delete %></td>
    </tr>
  <% end %>
</table>

app/views/comments/new.html.erb
<%= render 'comment' %>

app/views/comments/show.html.erb
Content: <%= @comment.content %>

app/views/home/index.html.erb
<%= @message %>
<%= link_to 'Users', users_path %>

app/views/layouts/_user_header.html.erb
<div class='navbar bg-light'>
  <div class="container">
    <span class='navbar-text'>
      <% if current_user %>
        <% if current_user.avatar.persisted? %>
          <%= image_tag current_user.avatar, height: '20px' %>
        <% end %>
        <%= "Logged as #{current_user.name}" %>
        <%= link_to 'Sign out', destroy_user_session_path, method: :delete %>
      <% else %>
        <%= link_to 'Sign in', new_user_session_path %>
        <%= link_to 'Register', new_user_registration_path %>
      <% end %>
    </span>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RubyOnRailsCourse</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/user_header' %>
    <% if flash[:notice] %>
      <div class="container">
        <div class="alert alert-primary" role="alert">
          <%= flash[:notice] %>
        </div>
      </div>
    <% end %>

    <% if flash[:alert] %>
      <div class="container">
        <div class="alert alert-danger" role="alert">
          <%= flash[:alert] %>
        </div>
      </div>
    <% end %>
    <div class='container'>
      <%= yield %>
    </div>
  </body>
</html>

app/views/posts/_post.html.erb
<%= form_with model: @post do |form| %>
  <div class='mb-3 col-md-2'>
    <%= form.label :title %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>
  <div class='mb-3 col-md-2'>
    <%= form.label :image %>
    <%= form.file_field :image, accept: 'image/png, image/jpg, image/jpeg', class: 'form-control' %>
  </div>
  <div class='mb-3 col-md-2'>
    <%= form.label :body %>
    <%= form.text_field :body, class: 'form-control' %>
  </div>
  <%= form.submit 'Save', class: 'btn btn-success' %>
<% end %>

app/views/posts/edit.html.erb
<%= render 'post' %>

app/views/posts/index.html.erb
<%= link_to 'Add New Post', new_post_path, class: 'btn btn-primary link-warning' %>

<h1>Posts</h1>
<table class="table">
  <tr>
    <th>Post ID</th>
    <th>Post Title</th>
    <th>Edit</th>
    <th>Delete</th>
  </tr>
  <% @posts.each do |post| %>
    <tr>
      <td><%= post.id %></td>
      <td><%= link_to post.title, post_path(post) %></td>
      <td><%= link_to 'Edit Post', edit_post_path(post) %></td>
      <td><%= link_to 'Delete Post', post_path(post), method: :delete %></td>
    </tr>
  <% end %>
</table>

<%= paginate @posts %>
<%= page_entries_info @posts, entry_name: 'Posts' %>

app/views/posts/new.html.erb
<%= render 'post' %>

app/views/posts/show.html.erb
<% presenter = PostPresenter.new(@post) %>
Title: <%= presenter.parsed_title %>
Body: <%= presenter.body %>
<% if presenter.image.persisted? %>
  Image: <%= image_tag presenter.image, width: '100px' %>
<% end %>

Comments:
<% @comments.each do |comment| %>
  <% comment_presenter = CommentPresenter.new(comment) %>
  <%= comment_presenter.parsed_content %>
<% end %>

app/views/users/_new_user_modal.html.erb
<div class="modal fade" id="newUserModal" tabindex="-1" aria-labelledby="newUserModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="newUserModalLabel">Add new user</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <%= form_with model: @user do |form| %>
        <div class="modal-body">
          <div class='mb-3 col-md-6'>
            <%= form.label :name %>
            <%= form.text_field :name, class: 'form-control' %>
          </div>
          <div class='mb-3 col-md-6'>
            <%= form.label :email %>
            <%= form.email_field :email, class: 'form-control' %>
          </div>
          <div class='mb-3 col-md-6'>
            <%= form.label :password %>
            <%= form.password_field :password, class: 'form-control' %>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
          <%= form.submit 'Create User', class: 'btn btn-success' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/_user.html.erb
 <%= form_with model: @user do |form| %>
  <div class='mb-3 col-md-2'>
    <%= form.label :name %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>
  <div class='mb-3 col-md-2'>
    <%= form.label :email %>
    <%= form.email_field :email, class: 'form-control' %>
  </div>
  <div class='mb-3 col-md-2'>
    <%= form.label :password %>
    <%= form.password_field :password, class: 'form-control' %>
  </div>
   <%= form.submit 'Create User', class: 'btn btn-success' %>
 <% end %>

app/views/users/edit.html.erb
<%= render 'user' %>

app/views/users/index.html.erb
<button type="button" class="btn btn-primary link-warning" data-bs-toggle="modal" data-bs-target="#newUserModal">
  Add New User
</button>

<%= image_tag "logo-2.svg", class: 'binar-logo' %>

<h1 class='users-header'>Users</h1>
<table class="table">
  <tr>
    <th>User ID</th>
    <th>User Name</th>
    <th>Edit</th>
    <th>Delete</th>
  </tr>
  <% @users.each do |user| %>
    <tr>
      <td><%= user.id %></td>
      <td><%= link_to user.name, user_path(user) %></td>
      <td><%= link_to 'Edit User', edit_user_path(user) %></td>
      <td><%= link_to 'Delete User', user_path(user), method: :delete %></td>
    </tr>
  <% end %>
</table>

<%= render 'new_user_modal' %>

app/views/users/new.html.erb
<%= render 'user' %>

app/views/users/show.html.erb
<%= @user.name %>